//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMW1.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMW1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 8.100000000000000000e+01 1.870000000000000000e+02
        ///8.800000000000000000e+01 2.150000000000000000e+02
        ///9.400000000000000000e+01 2.420000000000000000e+02
        ///1.000000000000000000e+02 2.670000000000000000e+02
        ///1.110000000000000000e+02 2.880000000000000000e+02
        ///1.280000000000000000e+02 3.040000000000000000e+02
        ///1.480000000000000000e+02 3.150000000000000000e+02
        ///1.660000000000000000e+02 3.250000000000000000e+02
        ///1.860000000000000000e+02 3.290000000000000000e+02
        ///2.050000000000000000e+02 3.250000000000000000e+02
        ///2.2300000000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 1.100000000000000000e+02 1.840000000000000000e+02
        ///1.020000000000000000e+02 2.050000000000000000e+02
        ///9.900000000000000000e+01 2.270000000000000000e+02
        ///1.010000000000000000e+02 2.480000000000000000e+02
        ///1.030000000000000000e+02 2.700000000000000000e+02
        ///1.080000000000000000e+02 2.930000000000000000e+02
        ///1.160000000000000000e+02 3.130000000000000000e+02
        ///1.250000000000000000e+02 3.300000000000000000e+02
        ///1.430000000000000000e+02 3.400000000000000000e+02
        ///1.670000000000000000e+02 3.440000000000000000e+02
        ///1.9500000000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 1.480000000000000000e+02 2.740000000000000000e+02
        ///1.530000000000000000e+02 3.140000000000000000e+02
        ///1.600000000000000000e+02 3.530000000000000000e+02
        ///1.690000000000000000e+02 3.910000000000000000e+02
        ///1.840000000000000000e+02 4.260000000000000000e+02
        ///2.070000000000000000e+02 4.580000000000000000e+02
        ///2.390000000000000000e+02 4.820000000000000000e+02
        ///2.760000000000000000e+02 5.020000000000000000e+02
        ///3.150000000000000000e+02 5.060000000000000000e+02
        ///3.510000000000000000e+02 4.970000000000000000e+02
        ///3.8100000000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _81 {
            get {
                return ResourceManager.GetString("_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 2.040000000000000000e+02 2.000000000000000000e+02
        ///2.100000000000000000e+02 2.260000000000000000e+02
        ///2.190000000000000000e+02 2.520000000000000000e+02
        ///2.280000000000000000e+02 2.770000000000000000e+02
        ///2.390000000000000000e+02 3.010000000000000000e+02
        ///2.570000000000000000e+02 3.210000000000000000e+02
        ///2.790000000000000000e+02 3.370000000000000000e+02
        ///3.030000000000000000e+02 3.490000000000000000e+02
        ///3.290000000000000000e+02 3.500000000000000000e+02
        ///3.520000000000000000e+02 3.430000000000000000e+02
        ///3.7300000000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _91 {
            get {
                return ResourceManager.GetString("_91", resourceCulture);
            }
        }
    }
}
